contexts:
  - Book a flight from NYC to BOS departing on Jun 9, 2023 and returning on Jun 15, 2023
  # - Book a flight from Chicago to Washington DC departing on Jul 4, 2023 and returning on Jul 15
  #- Book a flight from SFO to DTW departing on Aug 15, 2023 and returning the week after
  #- Book a flight from Denver to Houston departing on Sep 21, 2023 and returning on Oct 3
  #- Book a flight from Seattle to Detroit departing on Nov 4, 2023 and returning on Dec 2, 2023
  #- Book a flight from Detroit to Atlanta departing on October 2, 2023 and returning on Dec 15

urls:
  # - https://airlinecrm.awsdev.anonymous.com/evaluate?scenario=udkfc3o9rpt2kicp6jtw
  # - https://www.jetblue.com
  - https://www.aa.com
  #- https://www.united.com

num_episodes: 1
save_dir: ${hydra:runtime.cwd}/data/demos/liveweb/